root.option_add("*tearOff", 0)
options_bar = Menu(root)
root['menu'] = options_bar
options_menu = Menu(options_bar)
options_auto_flag = Menu(options_menu)
options_difficulty = Menu(options_menu)
options_theme = Menu(options_menu)

options_bar.add_cascade(menu=options_menu, label="Options")
options_menu.add_command(label="New Game", command=reset_game, accelerator="Ctrl+N")
options_menu.add_separator()
options_menu.add_cascade(menu=options_theme, label="Theme")
options_menu.add_command(label="Grid size...", command=change_grid_size, accelerator="Ctrl+G")
options_menu.add_cascade(menu=options_auto_flag, label="Auto reveal tiles")
options_menu.add_cascade(menu=options_difficulty, label="Difficulty")
options_auto_flag.add_radiobutton(label="Double click", variable=auto_reveal_var, value=2, command=lambda: set_info_var('ar'))
options_auto_flag.add_radiobutton(label="Single click", variable=auto_reveal_var, value=1, command=lambda: set_info_var('ar'))
options_auto_flag.add_radiobutton(label="Off", variable=auto_reveal_var, value=0, command=lambda: set_info_var('ar'))
options_difficulty.add_radiobutton(label="Easy", variable=difficulty_var, value="Easy",  command=lambda: set_info_var('d'))
options_difficulty.add_radiobutton(label="Normal", variable=difficulty_var, value="Normal",  command=lambda: set_info_var('d'))
options_difficulty.add_radiobutton(label="Hard", variable=difficulty_var, value="Hard",  command=lambda: set_info_var('d'))
options_difficulty.add_radiobutton(label="Deadly", variable=difficulty_var, value="Deadly",  command=lambda: set_info_var('d'))
options_theme.add_radiobutton(label="Light", variable=game_theme, value='light', command=lambda: stylize('light'))
options_theme.add_radiobutton(label="Dark", variable=game_theme, value='dark', command=lambda: stylize('dark'))
options_theme.add_radiobutton(label="Dark red", variable=game_theme, value='dark_red', command=lambda:stylize('dark_red'))
options_theme.add_radiobutton(label="Dark blue", variable=game_theme, value='dark_blue', command=lambda:stylize('dark_blue'))
options_theme.add_radiobutton(label="Ugly", variable=game_theme, value='test', command=lambda:stylize('test'))