# main = ttk.Frame(root, borderwidth=3, relief='sunken')
top_bar = ttk.Frame(root)
reset = ttk.Button(top_bar, text="BombSniffer", command=reset_game)
self.g_over_alert = ttk.Label(root)
sep = ttk.Separator(root, orient=HORIZONTAL)
info = ttk.Frame(root)
info_grid = ttk.Label(info)
info_reveal = ttk.Label(info)
info_timer = ttk.Label(top_bar)
info_timer['text'] = "00:00"

# main.grid(column=0, row=1, padx=20, pady=(0, 20), sticky=(N, S, E, W))
top_bar.grid(column=0, row=0, pady=20, padx=20, sticky='NSEW')
reset.grid(column=1, row=0)
info_timer.grid(column=1, row=1)
sep.grid(column=0, row=2, sticky='EW')
info.grid(column=0, row=3, sticky='EW')
info_grid.grid(column=0, row=0, sticky='W', padx=(20, 0))
info_reveal.grid(column=1, row=0, sticky='E', padx=(0, 20))

root.columnconfigure(1, weight=1)
root.rowconfigure(0, weight=1)
top_bar.columnconfigure(1, weight=1)
top_bar.rowconfigure(0, weight=1)
info.columnconfigure(1, weight=1)
root.resizable(FALSE, FALSE)

root.bind('<Control-n>', lambda e: reset_game())
root.bind('<Control-g>', lambda e: change_grid_size())
top_bar.bind('<3>', lambda e: options_menu.post(e.x_root, e.y_root))
info_grid.bind('<1>', lambda e: change_grid_size())
info_reveal.bind('<1>', lambda e: options_auto_flag.post(e.x_root, e.y_root))
info_reveal.bind('<3>', lambda e: options_auto_flag.post(e.x_root, e.y_root))

main = ttk.Frame(root, borderwidth=3, relief='sunken')
main.grid(column=0, row=1, padx=20, pady=(0, 20), sticky='NSEW')